name: CI - build traditional image

on:
  push:
    branches-ignore:
      - "main"
    paths:
      - "feature/**"
      - "traditional/**"
      - ".github/**"

  pull_request:
    paths:
      - "feature/**"
      - "traditional/**"
      - ".github/**"

  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

  workflow_dispatch: ~

jobs:
  ubuntu:
    name: "Build traditional image on Ubuntu"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ "ubuntu-latest" ]

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"

      - name: "Install Buildx"
        id: "buildx"
        uses: "crazy-max/ghaction-docker-buildx@v1"
        with:
          buildx-version: latest

      - name: "Build and Push"
        run: |
          docker buildx build \
          --no-cache \
          --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 traditional/ubuntu/

  alpine:
    name: "Build traditional image on Alpine"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ "ubuntu-latest" ]

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v3"

      - name: "Install Buildx"
        id: "buildx"
        uses: "crazy-max/ghaction-docker-buildx@v1"
        with:
          buildx-version: latest

      - name: "Build and Push"
        run: |
          docker buildx build \
          --no-cache \
          --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 traditional/alpine/
